import os
import re
import base64

def get_base64_font(font_path):
    with open(font_path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode('utf-8')
    ext = os.path.splitext(font_path)[1].lower()
    mime_type = "font/woff2" if ext == ".woff2" else "font/woff"
    return f"data:{mime_type};charset=utf-8;base64,{encoded}"

def inline_css_and_fonts(html_path):
    with open(html_path, 'r', encoding='utf-8') as f:
        html_content = f.read()

    # Find all stylesheet links
    # Match <link rel="stylesheet" href="..."> and <link rel="stylesheet" href="..." />
    link_pattern = re.compile(r'<link\s+rel="stylesheet"\s+href="([^"]+)"\s*/?>')
    
    def replacer(match):
        css_path = match.group(1)
        # Handle relative path from the html file
        full_css_path = os.path.join(os.path.dirname(html_path), css_path)
        
        if not os.path.exists(full_css_path):
            print(f"Warning: Stylesheet {full_css_path} not found.")
            return match.group(0)

        with open(full_css_path, 'r', encoding='utf-8') as f:
            css_content = f.read()

        # If it's a font CSS file, inline the actual font files as base64
        font_url_pattern = re.compile(r'url\((?!data:)[\'"]?([^\'")\n]+)[\'"]?\)')
        
        def font_replacer(font_match):
            font_rel_path = font_match.group(1)
            # Paths in CSS are relative to the CSS file itself
            full_font_path = os.path.join(os.path.dirname(full_css_path), font_rel_path)
            
            if os.path.exists(full_font_path) and os.path.isfile(full_font_path):
                print(f"Inlining font: {full_font_path}")
                base64_data = get_base64_font(full_font_path)
                return f"url('{base64_data}')"
            return font_match.group(0)

        if "fonts" in css_path:
            css_content = font_url_pattern.sub(font_replacer, css_content)

        return f'<style>\n/* Inlined from {css_path} */\n{css_content}\n</style>'

    # Process all stylesheet links
    html_content = link_pattern.sub(replacer, html_content)
    return html_content

def generate_cpp_header(html_content, output_header_path):
    encoded = html_content.encode('utf-8')
    hex_values = [f"0x{b:02x}" for b in encoded]
    hex_values.append("0x00") # null terminator for C-string safety
    
    lines = []
    for i in range(0, len(hex_values), 12):
        lines.append("    " + ", ".join(hex_values[i:i+12]))
        
    array_body = ",\n".join(lines)
    
    cpp_content = f"""#pragma once

// Auto-generated by build_assets.py
// Contains the fully inlined HTML, CSS, and base64 fonts for OmniEncrypt

static const unsigned char HTML_CONTENT[] = {{
{array_body}
}};
"""
    with open(output_header_path, 'w', encoding='utf-8') as f:
        f.write(cpp_content)
    print(f"Successfully generated {output_header_path}")

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    html_file = os.path.join(script_dir, "code.html")
    header_file = os.path.join(script_dir, "html_content.h")
    
    print(f"Processing {html_file}...")
    final_html = inline_css_and_fonts(html_file)
    generate_cpp_header(final_html, header_file)
